/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.DBMS_GUI;

import com.DBMS_Model.DBMS_DAO;

/**
 *
 * @author Abdul Jabbar
 */
public class Anomalies_Page extends javax.swing.JFrame {

    /**
     * Creates new form Anomalies_Page
     */
    static Selection_Page sp=new Selection_Page();
    static DBMS_DAO db=new DBMS_DAO();
    static Main_Page mp=new Main_Page();
    static Main_Page e;
    public Anomalies_Page() {
        initComponents();
    }
    public Anomalies_Page(Main_Page e){
        initComponents();
        this.e=e;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JPanel();
        employee = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emp_label = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        emp_button_table = new javax.swing.JButton();
        emp_id = new javax.swing.JTextField();
        emp_name = new javax.swing.JTextField();
        emp_email = new javax.swing.JTextField();
        emp_ph = new javax.swing.JTextField();
        emp_des = new javax.swing.JTextField();
        emp_add = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        course = new javax.swing.JPanel();
        Course_title = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        course_label = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Course_hours = new javax.swing.JTextField();
        Course_pre = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Course_area = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        Course_emp_id = new javax.swing.JTextField();
        course_button = new javax.swing.JButton();
        backBtn1 = new javax.swing.JButton();
        courseBook = new javax.swing.JPanel();
        book_title = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        book_id = new javax.swing.JTextField();
        courseBook_label = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        book_code = new javax.swing.JTextField();
        courseBook_button = new javax.swing.JButton();
        backBtn2 = new javax.swing.JButton();
        bookAuthor = new javax.swing.JPanel();
        author = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        author_id = new javax.swing.JTextField();
        bookAuthor_label = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        author_book_id = new javax.swing.JTextField();
        bookAuthor_button = new javax.swing.JButton();
        backBtn3 = new javax.swing.JButton();
        notes = new javax.swing.JPanel();
        course_notes_id = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        notes_id = new javax.swing.JTextField();
        notes_label = new javax.swing.JLabel();
        notes_submit = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        emp_notes_id = new javax.swing.JTextField();
        notes_button = new javax.swing.JButton();
        backBtn4 = new javax.swing.JButton();
        ttp = new javax.swing.JPanel();
        course_ttp_code = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        ttp_link = new javax.swing.JTextField();
        ttp_label = new javax.swing.JLabel();
        ttp_button = new javax.swing.JButton();
        ttp_id = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        backBtn5 = new javax.swing.JButton();
        publications = new javax.swing.JPanel();
        pub_type = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        pub_title = new javax.swing.JTextField();
        publication_label = new javax.swing.JLabel();
        emp_pub_id = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        pub_year = new javax.swing.JTextField();
        publication_button = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        pub_id = new javax.swing.JTextField();
        backBtn6 = new javax.swing.JButton();
        project = new javax.swing.JPanel();
        pro_title = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        pro_id = new javax.swing.JTextField();
        project_label = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        pro_batch = new javax.swing.JTextField();
        pro_supervior = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        pro_type = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        pro_submit = new javax.swing.JTextField();
        project_button = new javax.swing.JButton();
        backBtn7 = new javax.swing.JButton();
        thesis = new javax.swing.JPanel();
        thesis_title = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        thesis_id = new javax.swing.JTextField();
        thesis_label = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        thesis_batch = new javax.swing.JTextField();
        pro_thesis_id = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        thesis_type = new javax.swing.JTextField();
        thesis_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        home.setLayout(new java.awt.CardLayout());

        jLabel1.setText("EMP_ID");

        jLabel9.setText("EMP_Name");

        emp_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        emp_label.setText("Employee");

        jLabel11.setText("EMP_Email");

        jLabel12.setText("EMP_Phone");

        jLabel13.setText("EMP_Address");

        jLabel14.setText("EMP_Designation");

        emp_button_table.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        emp_button_table.setText("Insert");
        emp_button_table.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emp_button_tableActionPerformed(evt);
            }
        });

        emp_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        emp_name.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        emp_email.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        emp_ph.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        emp_des.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        emp_add.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeeLayout = new javax.swing.GroupLayout(employee);
        employee.setLayout(employeeLayout);
        employeeLayout.setHorizontalGroup(
            employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLayout.createSequentialGroup()
                        .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 659, Short.MAX_VALUE))
                    .addGroup(employeeLayout.createSequentialGroup()
                        .addGroup(employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_email, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(194, 194, 194)
                        .addGroup(employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(emp_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emp_des, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(emp_add, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(0, 257, Short.MAX_VALUE))))
            .addGroup(employeeLayout.createSequentialGroup()
                .addGroup(employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147)
                        .addComponent(emp_label))
                    .addGroup(employeeLayout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(emp_button_table)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        employeeLayout.setVerticalGroup(
            employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeeLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp_ph, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emp_des, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emp_add, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(employeeLayout.createSequentialGroup()
                .addGroup(employeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeeLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(emp_label))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, employeeLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(11, 11, 11)
                .addComponent(emp_name, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(emp_email, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(emp_button_table)
                .addGap(78, 78, 78))
        );

        home.add(employee, "card2");

        Course_title.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel2.setText("course_code");

        jLabel15.setText("course_title");

        course_code.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        course_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        course_label.setText("Course");

        jLabel17.setText("credit_hours");

        Course_hours.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        Course_pre.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel18.setText("knowlege_area");

        jLabel19.setText("pre_requisite");

        Course_area.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel20.setText("emp_id");

        Course_emp_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        course_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        course_button.setText("Insert");
        course_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                course_buttonActionPerformed(evt);
            }
        });

        backBtn1.setText("Back");
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout courseLayout = new javax.swing.GroupLayout(course);
        course.setLayout(courseLayout);
        courseLayout.setHorizontalGroup(
            courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course_hours, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(Course_title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Course_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Course_area, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Course_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel20))
                .addGap(286, 286, 286))
            .addGroup(courseLayout.createSequentialGroup()
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(course_label))
                    .addGroup(courseLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(course_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        courseLayout.setVerticalGroup(
            courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(courseLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Course_area, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Course_pre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addComponent(Course_emp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(courseLayout.createSequentialGroup()
                        .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(course_label)
                            .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Course_title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17)
                                .addGap(60, 60, 60))
                            .addComponent(Course_hours, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(course_button)
                .addGap(65, 65, 65))
        );

        home.add(course, "card2");

        book_title.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel3.setText("book_id");

        jLabel21.setText("book_title");

        book_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        courseBook_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        courseBook_label.setText("Course_Book");

        jLabel23.setText("course_code");

        book_code.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        courseBook_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        courseBook_button.setText("Insert");
        courseBook_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseBook_buttonActionPerformed(evt);
            }
        });

        backBtn2.setText("Back");
        backBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout courseBookLayout = new javax.swing.GroupLayout(courseBook);
        courseBook.setLayout(courseBookLayout);
        courseBookLayout.setHorizontalGroup(
            courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseBookLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(courseBookLayout.createSequentialGroup()
                        .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(book_code, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(courseBookLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(347, 347, 347)
                        .addComponent(jLabel23))
                    .addComponent(jLabel21))
                .addGap(0, 312, Short.MAX_VALUE))
            .addGroup(courseBookLayout.createSequentialGroup()
                .addGroup(courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(courseBookLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140)
                        .addComponent(courseBook_label))
                    .addGroup(courseBookLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(courseBook_button)))
                .addGap(298, 298, 298))
        );
        courseBookLayout.setVerticalGroup(
            courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(courseBookLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseBook_label)
                    .addComponent(backBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(courseBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(book_code, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addComponent(book_title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(courseBook_button)
                .addGap(65, 65, 65))
        );

        home.add(courseBook, "card2");

        author.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel4.setText("author_id");

        jLabel27.setText("author name");

        author_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        bookAuthor_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bookAuthor_label.setText("Book_Author");

        jLabel29.setText("book_id");

        author_book_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        bookAuthor_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bookAuthor_button.setText("Insert");
        bookAuthor_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookAuthor_buttonActionPerformed(evt);
            }
        });

        backBtn3.setText("Back");
        backBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bookAuthorLayout = new javax.swing.GroupLayout(bookAuthor);
        bookAuthor.setLayout(bookAuthorLayout);
        bookAuthorLayout.setHorizontalGroup(
            bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookAuthorLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(author_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addGap(306, 306, 306))
            .addGroup(bookAuthorLayout.createSequentialGroup()
                .addGroup(bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bookAuthorLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(bookAuthor_label))
                    .addGroup(bookAuthorLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(bookAuthor_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bookAuthorLayout.setVerticalGroup(
            bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bookAuthorLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookAuthor_label)
                    .addComponent(backBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bookAuthorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(author_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(author_book_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(author, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108)
                .addComponent(bookAuthor_button)
                .addGap(65, 65, 65))
        );

        home.add(bookAuthor, "card2");

        course_notes_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel5.setText("note_id");

        jLabel33.setText("course_code");

        notes_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        notes_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        notes_label.setText("Notes");

        notes_submit.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel36.setText("emp_id");

        jLabel37.setText("submitted");

        emp_notes_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        notes_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        notes_button.setText("Insert");
        notes_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notes_buttonActionPerformed(evt);
            }
        });

        backBtn4.setText("Back");
        backBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout notesLayout = new javax.swing.GroupLayout(notes);
        notes.setLayout(notesLayout);
        notesLayout.setHorizontalGroup(
            notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notes_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33)
                    .addComponent(course_notes_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emp_notes_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(notes_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addGap(288, 288, 288))
            .addGroup(notesLayout.createSequentialGroup()
                .addGroup(notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(notesLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(notes_button))
                    .addGroup(notesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(backBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(notes_label)))
                .addContainerGap(590, Short.MAX_VALUE))
        );
        notesLayout.setVerticalGroup(
            notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notesLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(notesLayout.createSequentialGroup()
                        .addGroup(notesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(notes_label)
                            .addComponent(backBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notes_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(course_notes_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(notesLayout.createSequentialGroup()
                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(emp_notes_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notes_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(97, 97, 97)
                .addComponent(notes_button)
                .addGap(79, 79, 79))
        );

        home.add(notes, "card2");

        course_ttp_code.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel6.setText("ttp_link");

        jLabel39.setText("course_code");

        ttp_link.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        ttp_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        ttp_label.setText("TTP");

        ttp_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ttp_button.setText("Insert");
        ttp_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ttp_buttonActionPerformed(evt);
            }
        });

        ttp_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel16.setText("ttp_id");

        backBtn5.setText("Back");
        backBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ttpLayout = new javax.swing.GroupLayout(ttp);
        ttp.setLayout(ttpLayout);
        ttpLayout.setHorizontalGroup(
            ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ttpLayout.createSequentialGroup()
                .addGroup(ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ttpLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ttp_link, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(ttp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(131, 131, 131)
                        .addGroup(ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(course_ttp_code, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ttpLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(backBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138)
                        .addComponent(ttp_label))
                    .addGroup(ttpLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(ttp_button)))
                .addContainerGap(327, Short.MAX_VALUE))
        );
        ttpLayout.setVerticalGroup(
            ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ttpLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ttp_label)
                    .addComponent(backBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addGroup(ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ttpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_ttp_code, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ttp_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ttp_link, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(ttp_button)
                .addGap(65, 65, 65))
        );

        home.add(ttp, "card2");

        pub_type.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel7.setText("pub_title");

        jLabel45.setText("pub_type");

        pub_title.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        publication_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        publication_label.setText("Publication");

        emp_pub_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel48.setText("pub_year");

        jLabel49.setText("emp_id");

        pub_year.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        publication_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        publication_button.setText("Insert");
        publication_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publication_buttonActionPerformed(evt);
            }
        });

        jLabel22.setText("Pub_id");

        pub_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        backBtn6.setText("Back");
        backBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout publicationsLayout = new javax.swing.GroupLayout(publications);
        publications.setLayout(publicationsLayout);
        publicationsLayout.setHorizontalGroup(
            publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicationsLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pub_title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel45)
                    .addComponent(pub_type, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel22)
                    .addComponent(pub_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pub_year, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(emp_pub_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48))
                .addGap(281, 281, 281))
            .addGroup(publicationsLayout.createSequentialGroup()
                .addGroup(publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publicationsLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(backBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(publication_label))
                    .addGroup(publicationsLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(publication_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        publicationsLayout.setVerticalGroup(
            publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(publicationsLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(publication_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 342, Short.MAX_VALUE)
                .addComponent(publication_button)
                .addGap(65, 65, 65))
            .addGroup(publicationsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pub_year, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pub_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pub_title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel49)
                .addGroup(publicationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(publicationsLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(emp_pub_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(publicationsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel45)
                        .addGap(18, 18, 18)
                        .addComponent(pub_type, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        home.add(publications, "card2");

        pro_title.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel8.setText("pro_id");

        jLabel51.setText("pro_title");

        pro_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        project_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        project_label.setText("Project");

        jLabel53.setText("batch");

        pro_batch.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        pro_supervior.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel54.setText("pro_type");

        jLabel55.setText("supervior");

        pro_type.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel56.setText("submitted");

        pro_submit.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        project_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        project_button.setText("Insert");
        project_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                project_buttonActionPerformed(evt);
            }
        });

        backBtn7.setText("Back");
        backBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout projectLayout = new javax.swing.GroupLayout(project);
        project.setLayout(projectLayout);
        projectLayout.setHorizontalGroup(
            projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pro_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pro_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(pro_title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pro_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pro_type, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(pro_supervior, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(jLabel56))
                .addGap(286, 286, 286))
            .addGroup(projectLayout.createSequentialGroup()
                .addGroup(projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(projectLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(backBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(project_label))
                    .addGroup(projectLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(project_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projectLayout.setVerticalGroup(
            projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pro_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(projectLayout.createSequentialGroup()
                        .addGroup(projectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(project_label)
                            .addComponent(backBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pro_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel51)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pro_title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel53)
                        .addGap(60, 60, 60))
                    .addGroup(projectLayout.createSequentialGroup()
                        .addComponent(jLabel54, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pro_type, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pro_supervior, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel56)
                        .addGap(18, 18, 18)
                        .addComponent(pro_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(project_button)
                .addGap(65, 65, 65))
        );

        home.add(project, "card2");

        thesis_title.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel10.setText("thesis_id");

        jLabel52.setText("thesis_title");

        thesis_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        thesis_label.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        thesis_label.setText("Thesis");

        jLabel57.setText("batch");

        thesis_batch.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        pro_thesis_id.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        jLabel58.setText("thesis_type");

        jLabel59.setText("pro_id");

        thesis_type.setFont(new java.awt.Font("Times New Roman", 0, 20)); // NOI18N

        thesis_button.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        thesis_button.setText("Insert");
        thesis_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thesis_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thesisLayout = new javax.swing.GroupLayout(thesis);
        thesis.setLayout(thesisLayout);
        thesisLayout.setHorizontalGroup(
            thesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thesisLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(thesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thesis_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thesis_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(thesis_title, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel57))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 181, Short.MAX_VALUE)
                .addGroup(thesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thesis_type, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(pro_thesis_id, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel58))
                .addGap(286, 286, 286))
            .addGroup(thesisLayout.createSequentialGroup()
                .addGroup(thesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thesisLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(thesis_label))
                    .addGroup(thesisLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addComponent(thesis_button)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        thesisLayout.setVerticalGroup(
            thesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thesisLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(thesisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thesis_batch, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(thesisLayout.createSequentialGroup()
                        .addComponent(thesis_label)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(thesis_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel52)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(thesis_title, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel57)
                        .addGap(60, 60, 60))
                    .addGroup(thesisLayout.createSequentialGroup()
                        .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(thesis_type, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel59)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pro_thesis_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(thesis_button)
                .addGap(65, 65, 65))
        );

        home.add(thesis, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    String comboBox;
    String button;
    
    
    public void setComboBox(String aa,String bu){
        comboBox=aa;
        button=bu;
        System.out.println(comboBox+" -0");
        System.out.println(button+" -0");
        if(comboBox.equalsIgnoreCase("Employee")){
            if(button.equalsIgnoreCase("Update")){
                emp_button_table.setText("Update");
                System.out.println(comboBox+" -1");
                System.out.println(button+" -1");
            }else if(button.equalsIgnoreCase("Delete")){
                emp_button_table.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                emp_button_table.setText("Insert");
            }
            emp_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Course")){
            if(button.equalsIgnoreCase("Update")){
                course_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                course_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                course_button.setText("Insert");
            }
            course_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Course_Book")){
            if(button.equalsIgnoreCase("Update")){
                courseBook_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                courseBook_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                courseBook_button.setText("Insert");
            }
            courseBook_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Book_Author")){
            if(button.equalsIgnoreCase("Update")){
                bookAuthor_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                bookAuthor_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                bookAuthor_button.setText("Insert");
            }
            bookAuthor_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Notes")){
            if(button.equalsIgnoreCase("Update")){
                notes_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                notes_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                notes_button.setText("Insert");
            }
            notes_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Project")){
            if(button.equalsIgnoreCase("Update")){
                project_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                project_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                project_button.setText("Insert");
            }
            project_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("TTP")){
            if(button.equalsIgnoreCase("Update")){
                ttp_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                ttp_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                ttp_button.setText("Insert");
            }
            ttp_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Thesis")){
            if(button.equalsIgnoreCase("Update")){
                thesis_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                thesis_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                thesis_button.setText("Insert");
            }
            thesis_label.setText(comboBox);
        }else if(comboBox.equalsIgnoreCase("Publication")){
            if(button.equalsIgnoreCase("Update")){
                publication_button.setText("Update");
            }else if(button.equalsIgnoreCase("Delete")){
                publication_button.setText("Delete");
            }else if(button.equalsIgnoreCase("Insert")){
                publication_button.setText("Insert");
            }
            publication_label.setText(comboBox);
        }
    }
    
    private void emp_button_tableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emp_button_tableActionPerformed
        // TODO add your handling code here:
        
        if(button.equalsIgnoreCase("Update")){
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Employee")){
                db.updateEmployee(emp_name.getText(),emp_email.getText(),emp_add.getText(),emp_des.getText(),emp_id.getText(),Integer.parseInt(emp_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            System.out.println("delete");
            db.deleteEmployee(emp_id.getText());
        }else if(button.equalsIgnoreCase("Insert")){
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Employee")){
                db.insertEmployee(emp_name.getText(),emp_email.getText(),emp_add.getText(),emp_des.getText(),emp_id.getText(),Integer.parseInt(emp_id.getText()));
                System.out.println("insert 1");
            }
        }
    }//GEN-LAST:event_emp_button_tableActionPerformed

    private void project_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_project_buttonActionPerformed
        // TODO add your handling code here:
        //DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            project_button.setText("Updeate");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Project")){
                db.updateProject(pro_title.getText(),Integer.parseInt(pro_batch.getText()),pro_type.getText(),pro_supervior.getText(),pro_submit.getText(),Integer.parseInt(pro_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            project_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("Project")){
                db.deleteProject(Integer.parseInt(pro_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            project_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Project")){
                db.insertProject(pro_title.getText(),pro_type.getText(),pro_submit.getText(),Integer.parseInt(pro_batch.getText()),Integer.parseInt(pro_id.getText()),pro_supervior.getText());
            }
        }
    }//GEN-LAST:event_project_buttonActionPerformed

    private void thesis_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thesis_buttonActionPerformed
        // TODO add your handling code here:
       // DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            thesis_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Thesis")){
                db.updateThesis(thesis_title.getText(),Integer.parseInt(thesis_batch.getText()),thesis_type.getText(),Integer.parseInt(pro_thesis_id.getText()),Integer.parseInt(thesis_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            thesis_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("Thesis")){
                db.deleteThesis(Integer.parseInt(thesis_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            thesis_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Thesis")){
                db.insertThesis(thesis_title.getText(),thesis_type.getText(),Integer.parseInt(thesis_batch.getText()),Integer.parseInt(thesis_id.getText()),Integer.parseInt(pro_thesis_id.getText()));
            }
        }
    }//GEN-LAST:event_thesis_buttonActionPerformed

    private void course_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_course_buttonActionPerformed
        // TODO add your handling code here:
        System.out.println(course_code.getText());
//        DBMS_DAO db=new DBMS_DAO();
        course_label.setText(comboBox);
        if(button.equalsIgnoreCase("Update")){
            course_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Course")){
                db.updateCourse(Course_title.getText(),Course_area.getText(),Course_pre.getText(),Integer.parseInt(course_code.getText()),Integer.parseInt(Course_hours.getText()), Course_emp_id.getText());
            }
        }else if(button.equalsIgnoreCase("Delete")){
            course_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("Course")){
                db.deleteCourse(Integer.parseInt(course_code.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            course_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Course")){
                db.insertCourse(Course_title.getText(),Course_area.getText(),Course_pre.getText(),Integer.parseInt(course_code.getText()),Integer.parseInt(Course_hours.getText()), Course_emp_id.getText());
            }
        }
    }//GEN-LAST:event_course_buttonActionPerformed

    private void courseBook_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseBook_buttonActionPerformed
        // TODO add your handling code here:
        System.out.println(book_id.getText());
//        DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            courseBook_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Course_Book")){
                db.updateCourseBook(book_title.getText(),Integer.parseInt(book_id.getText()),Integer.parseInt(book_code.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            courseBook_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("Course_Book")){
                db.deleteCourseBook(Integer.parseInt(book_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            courseBook_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Course_Book")){
                db.insertCourseBook(book_title.getText(),Integer.parseInt(book_id.getText()),Integer.parseInt(book_code.getText()));
            }
        }
    }//GEN-LAST:event_courseBook_buttonActionPerformed

    private void bookAuthor_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookAuthor_buttonActionPerformed
        // TODO add your handling code here:
//        DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            bookAuthor_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Book_Author")){
                db.updateBookAuthor(author.getText(),Integer.parseInt(author_book_id.getText()),Integer.parseInt(author_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            bookAuthor_button.setText("Delete");
            System.out.println("delete");
            db.deleteBookAuthor(Integer.parseInt(author_id.getText()));
        }else if(button.equalsIgnoreCase("Insert")){
            bookAuthor_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Book_Author")){
                db.insertBookAuthor(author.getText(),Integer.parseInt(author_book_id.getText()),Integer.parseInt(author_id.getText()));
            }
        }
    }//GEN-LAST:event_bookAuthor_buttonActionPerformed

    private void notes_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notes_buttonActionPerformed
        // TODO add your handling code here:
//        DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            notes_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Notes")){
                db.updateNotes(Integer.parseInt(notes_id.getText()),Integer.parseInt(emp_notes_id.getText()),notes_submit.getText(),Integer.parseInt(course_notes_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            notes_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("Notes")){
                db.deleteNotes(Integer.parseInt(notes_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            notes_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Notes")){
                db.insertNotes(notes_submit.getText(),Integer.parseInt(course_notes_id.getText()),Integer.parseInt(notes_id.getText()),Integer.parseInt(emp_notes_id.getText()));
            }
        }
    }//GEN-LAST:event_notes_buttonActionPerformed

    private void ttp_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ttp_buttonActionPerformed
        // TODO add your handling code here:
//        DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            ttp_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("TTP")){
                db.updateTtp(ttp_link.getText(),Integer.parseInt(course_ttp_code.getText()),Integer.parseInt(ttp_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            ttp_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("TTP")){
                db.deleteTtp(Integer.parseInt(ttp_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            ttp_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("TTP")){
                db.insertTtp(ttp_link.getText(),Integer.parseInt(course_ttp_code.getText()),Integer.parseInt(ttp_id.getText()));
            }
        }
    }//GEN-LAST:event_ttp_buttonActionPerformed

    private void publication_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publication_buttonActionPerformed
        // TODO add your handling code here:
//        DBMS_DAO db=new DBMS_DAO();
        if(button.equalsIgnoreCase("Update")){
            publication_button.setText("Update");
            System.out.println("udate");
            if(comboBox.equalsIgnoreCase("Publication")){
                db.updatePublication(pub_title.getText(),pub_type.getText(),Integer.parseInt(pub_year.getText()),emp_pub_id.getText(),Integer.parseInt(pub_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Delete")){
            publication_button.setText("Delete");
            System.out.println("delete");
            if(comboBox.equalsIgnoreCase("Publication")){
                db.deletePublication(Integer.parseInt(pub_id.getText()));
            }
        }else if(button.equalsIgnoreCase("Insert")){
            publication_button.setText("Insert");
            System.out.println("insert");
            if(comboBox.equalsIgnoreCase("Publication")){
                db.insertPublication(pub_title.getText(),pub_type.getText(),Integer.parseInt(pub_year.getText()),emp_pub_id.getText(),Integer.parseInt(pub_id.getText()));
            }
        }
    }//GEN-LAST:event_publication_buttonActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        // TODO add your handling code here:
         //this.setVisible(false);
       //new Main_Page().setVisible(true);
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void backBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn2ActionPerformed
        // TODO add your handling code here:
        
       System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn2ActionPerformed

    private void backBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn3ActionPerformed
        // TODO add your handling code here:
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn3ActionPerformed

    private void backBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn4ActionPerformed
        // TODO add your handling code here:
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn4ActionPerformed

    private void backBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn5ActionPerformed
        // TODO add your handling code here:
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn5ActionPerformed

    private void backBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn6ActionPerformed
        // TODO add your handling code here:
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn6ActionPerformed

    private void backBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn7ActionPerformed
        // TODO add your handling code here:
        System.out.println(sp.getButtonName());
        if(sp.getButtonName().equalsIgnoreCase("Admin")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getAdmin();
        }else if(sp.getButtonName().equalsIgnoreCase("Employee")){
            this.setVisible(false);
            mp.setVisible(true);
            mp.getEmployee();
        }
    }//GEN-LAST:event_backBtn7ActionPerformed

    public void emp(){
        home.removeAll();
        home.add(employee);
        home.repaint();
        home.revalidate();
    }
    public void emp1(){
        home.removeAll();
        home.add(course);
        home.repaint();
        home.revalidate();
    }
    public void emp2(){
        home.removeAll();
        home.add(courseBook);
        home.repaint();
        home.revalidate();
    }
    public void emp3(){
        home.removeAll();
        home.add(bookAuthor);
        home.repaint();
        home.revalidate();
    }
    public void emp4(){
        home.removeAll();
        home.add(notes);
        home.repaint();
        home.revalidate();
    }
    public void emp5(){
        home.removeAll();
        home.add(ttp);
        home.repaint();
        home.revalidate();
    }
    public void emp6(){
        home.removeAll();
        home.add(publications);
        home.repaint();
        home.revalidate();
    }
    public void emp7(){
        home.removeAll();
        home.add(project);
        home.repaint();
        home.revalidate();
    }
    public void emp8(){
        home.removeAll();
        home.add(thesis);
        home.repaint();
        home.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Anomalies_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Anomalies_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Anomalies_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Anomalies_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Anomalies_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Course_area;
    private javax.swing.JTextField Course_emp_id;
    private javax.swing.JTextField Course_hours;
    private javax.swing.JTextField Course_pre;
    private javax.swing.JTextField Course_title;
    private javax.swing.JTextField author;
    private javax.swing.JTextField author_book_id;
    private javax.swing.JTextField author_id;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JButton backBtn2;
    private javax.swing.JButton backBtn3;
    private javax.swing.JButton backBtn4;
    private javax.swing.JButton backBtn5;
    private javax.swing.JButton backBtn6;
    private javax.swing.JButton backBtn7;
    private javax.swing.JPanel bookAuthor;
    private javax.swing.JButton bookAuthor_button;
    private javax.swing.JLabel bookAuthor_label;
    private javax.swing.JTextField book_code;
    private javax.swing.JTextField book_id;
    private javax.swing.JTextField book_title;
    private javax.swing.JPanel course;
    private javax.swing.JPanel courseBook;
    private javax.swing.JButton courseBook_button;
    private javax.swing.JLabel courseBook_label;
    private javax.swing.JButton course_button;
    private javax.swing.JTextField course_code;
    private javax.swing.JLabel course_label;
    private javax.swing.JTextField course_notes_id;
    private javax.swing.JTextField course_ttp_code;
    private javax.swing.JTextField emp_add;
    private javax.swing.JButton emp_button_table;
    private javax.swing.JTextField emp_des;
    private javax.swing.JTextField emp_email;
    private javax.swing.JTextField emp_id;
    public javax.swing.JLabel emp_label;
    private javax.swing.JTextField emp_name;
    private javax.swing.JTextField emp_notes_id;
    private javax.swing.JTextField emp_ph;
    private javax.swing.JTextField emp_pub_id;
    private javax.swing.JPanel employee;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel notes;
    private javax.swing.JButton notes_button;
    private javax.swing.JTextField notes_id;
    private javax.swing.JLabel notes_label;
    private javax.swing.JTextField notes_submit;
    private javax.swing.JTextField pro_batch;
    private javax.swing.JTextField pro_id;
    private javax.swing.JTextField pro_submit;
    private javax.swing.JTextField pro_supervior;
    private javax.swing.JTextField pro_thesis_id;
    private javax.swing.JTextField pro_title;
    private javax.swing.JTextField pro_type;
    private javax.swing.JPanel project;
    private javax.swing.JButton project_button;
    private javax.swing.JLabel project_label;
    private javax.swing.JTextField pub_id;
    private javax.swing.JTextField pub_title;
    private javax.swing.JTextField pub_type;
    private javax.swing.JTextField pub_year;
    private javax.swing.JButton publication_button;
    private javax.swing.JLabel publication_label;
    private javax.swing.JPanel publications;
    private javax.swing.JPanel thesis;
    private javax.swing.JTextField thesis_batch;
    private javax.swing.JButton thesis_button;
    private javax.swing.JTextField thesis_id;
    private javax.swing.JLabel thesis_label;
    private javax.swing.JTextField thesis_title;
    private javax.swing.JTextField thesis_type;
    private javax.swing.JPanel ttp;
    private javax.swing.JButton ttp_button;
    private javax.swing.JTextField ttp_id;
    private javax.swing.JLabel ttp_label;
    private javax.swing.JTextField ttp_link;
    // End of variables declaration//GEN-END:variables
}
